SELECT cpp.no_certif,cpp.doc,cpp.fecha_emi,cpp.monto,cpp.Tipo_PP  FROM CC.dbo.CERTIF_PMM_PU cpp; 

SELECT dc.COMPONENTE,dc.MONTO_CC,dc.MONTO_PMM,dc.MONTO_PU,dc.APORTES_AFP,dc.NRO_DOCUMENTO,dc.FECHA_SELECCION,dc.SALUD,dc.NRO_MESES,dc.INTERIOR_MINA,dc.FECHA_PROCESO,dc.NRO_MINA,dc.TRAB_SIM 
FROM CC.dbo.DOC_COMPARATIVO dc; 

SELECT cp.COD,cp.ANIO,cp.MES,cp.DEBE,cp.HABER,cp.NRO_CHEQUE,cp.NRO_BAN,cp.FECHA_EMI,cp.C31  FROM PAGOS_P.dbo.chePU cp;

SELECT pb.FORMULARIO,pb.PORCENTAJE  FROM PAGOS_P.dbo.Pre_Beneficiarios pb;

SELECT pt.FORMULARIO,pt.NUM_CERTIF,pt.ANIOS_INSALUBRES,pt.MONTO_BASE,pt.REINTEGRO_DESDE,pt.REINTEGRO_HASTA,pt.REINTEGRO,pt.AGUINALDO,pt.RED_EDAD,pt.MESES_CNS
FROM PAGOS_P.dbo.Pre_Titulares pt;

SELECT tp.NUM_CERTIF,tp.FORMULARIO,tp.ANIOS_INSALUBRES,tp.FECHA_ALTA,tp.RESOLUCION  FROM PAGOS_P.dbo.Titular_PU tp;



